services:
  - type: web
    name: blogapp
    env: java
    buildCommand: "./mvnw clean install"  # If you have mvnw
    startCommand: "java -jar target/*.jar"
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
